"use client";

import {
  FileText,
  FileSpreadsheet,
  Globe,
  FileCode2,
} from "lucide-react";

const outputs = [
  {
    name: "DOCX",
    description: "Quick Reference Guide",
    icon: FileText,
  },
  {
    name: "PDF",
    description: "Printable Document",
    icon: FileSpreadsheet,
  },
  {
    name: "HTML",
    description: "Knowledge Portal",
    icon: Globe,
  },
  {
    name: "Markdown",
    description: "GitHub Documentation",
    icon: FileCode2,
  },
];

export default function OutputFormats() {
  return (
    <div className="rounded-xl border bg-white shadow-sm h-full">
      <div className="border-b p-5">
        <h2 className="text-xl font-semibold">
          Output Formats
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Documentation generated by the AI engine.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 p-5">
        {outputs.map((output) => {
          const Icon = output.icon;

          return (
            <div
              key={output.name}
              className="rounded-lg border p-4 hover:border-blue-500 hover:bg-slate-50 transition cursor-pointer"
            >
              <Icon className="h-8 w-8 text-blue-600" />

              <h3 className="mt-3 font-semibold">
                {output.name}
              </h3>

              <p className="mt-1 text-sm text-slate-500">
                {output.description}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}